[main]
author = "iivanovw7.dev"
name = "Igor Ivanov"
profession = "Frontend developer"
project = "https://github.com/iivanovw7/iivanovw7-dev"

[social]
email = "mailto:iivanovw7@gmail.com"
github = "https://github.com/iivanovw7"
linkedin = "https://www.linkedin.com/in/iivanovw7"
telegram = "https://t.me/iivanovw7"
twitter = "https://twitter.com/_IvanovIgor"

[[jobs]]
index = 0
end = "Present"
company = "Devexperts"
company_logo = "/assets/png/dx-logo.png"
location = "Porto, Portugal"
start = "Mar 2024"
position = "Frontend developer"
subtitle = "Working with React, TS, and a11y to create user-friendly interfaces for the Capital Markets industry."

[[jobs]]
index = 1
end = "Feb 2024"
company = "Mytona"
company_logo = "/assets/png/mytona-logo.png"
location = "Singapore"
position = "Frontend developer"
start = "Jan 2021"
subtitle = "Building polished software and web experiences using React / Mobx."

[[jobs]]
index = 2
company = "AB Technology"
company_logo = "/assets/png/ab-logo.png"
end = "Jan 2021"
location = "Saint-Petersburg, Russia"
start = "Feb 2019"
position = "Frontend developer"
subtitle = "Developed an online cinema projects using React / Redux and Angular."

[[jobs]]
index = 3
company = "BCC"
company_logo = "/assets/png/bcc-logo.png"
end = "Feb 2019"
location = "Saint-Petersburg, Russia"
position = "Engineer"
start = "Jan 2013"
subtitle = "Created logic for PLCs based on design documentation and implemented them in systems for production use."
