[main]
author = "iivanovw7"
title = "Igor Ivanov"
description = "Frontend developer"
project = "https://github.com/iivanovw7/iivanovw7-dev"
resume = "https://flowcv.com/resume/v6rbqr3rcs"

[social]
email = "mailto:iivanovw7@gmail.com"
github = "https://github.com/iivanovw7"
linkedin = "https://www.linkedin.com/in/iivanovw7"
telegram = "https://t.me/iivanovw7"
twitter = "https://twitter.com/_IvanovIgor"

[cards]
[cards.skills]
title = "I constantly try to improve my skills."
description = "I am interested in using my expertise to build well-constructed and user-friendly web applications"
[cards.contacts]
title = "Contact me"
description = "Make a contact via email or telegram."
