indent = 4
indent_css = 4
indent_html = 4
indent_js = 4
indent_json = 4
indent_less = 4
indent_scss = 4

max_line_length = 120

profile = "jinja"

close_out = true
close_out_js = true
close_void = true
close_void_tags = true

no_leading_space = true
no_trailing_space = true
